### ISSUE TITLE
Drag'n Dropping / Loading a file issue

### ISSUE THREAD

**Issue by xMinhx** [karlkirschner/scipro_assignments_grading#2]
Reading in a new JSON file without reloading the page may create an union of bullet points being selected between the previous json file and the new json file.

**Comment by erikautenrieth** [comment]
- It is meant that you should press the reset button before uploading json files. Then it should work. 
- But it is possible to implement the functionality that the current cache is cleared as soon as a json file is uploaded.

**Comment by xMinhx** [comment]
I think clearing the grading template on loading a new file would be bests. The other workflow may be prone to errors. Forgetting to press the reset button can happen.
