### ISSUE TITLE
Grades not updated after loading in new files

### ISSUE THREAD

**Issue by xMinhx** [karlkirschner/scipro_assignments_grading#3]
Loading in a new json file does not automatically update the grade.

**Comment by erikautenrieth** [comment]
- Here, the code base of Abanoub would have to be rewritten. The current code does not store the percentages of the table in the cache and therefore not in the json file.

**Comment by karlkirschner** [comment]
I did notice that as soon as I adjusted one of the values, the whole table corrected itself.

**Comment by xMinhx** [comment]
Maybe I can take a quick look into it in this week. I have an idea.
