### ISSUE TITLE
File creation and generation text issue

### ISSUE THREAD

**Issue by xMinhx** [karlkirschner/scipro_assignments_grading#4]
Generating the file without regenerating the text results in the json file to load the old text.
Maybe related to the union problem when loading in a new file without reloading the old file.

**Comment by erikautenrieth** [comment]
- I don't quite understand the issue. But you should press the reset button after each json file creation. Maybe I should create a workflow description on the top of the template.

**Comment by karlkirschner** [comment]
Could we have it such that if one loads a json file, it does so cleanly, with out existing selected buttons and feedback being added to it? Having to "Reset" the form (and "Clear File")  for every student solution (i.e. > 50 times) was prone to error. I ended up having to double check the forms. It also wasn't clear if one has to :Generate" the form and then "Download" the json and txt file, or whether I could make modification to the uploaded feedback and then directly select the "Download" buttons.

**Comment by erikautenrieth** [comment]
- I will implement the function: resets everything when a json file is uploaded (it should be ready this week). 
- The gradings can always be downloaded as JSON or Txt immediately without pressing Generate or Save Session. 
  For this, I would like to create a workflow description (see issue Grading Workflow Description)
